server:
  port: 8080
  
spring:
  application:
    name: gateway

zuul:
  routes:
    root-service:
      path: /rooty/**
      serviceId: root-service
    users-service:
      path: /userr/**
      serviceId: users-service
